const { getDefaultConfig } = require('expo/metro-config');
const path = require('path');
const fs = require('fs');

const projectRoot = __dirname;
const monorepoRoot = path.resolve(projectRoot, '../..');
const appDir = path.resolve(projectRoot, 'app');

// Required before getDefaultConfig so expo-router picks it up
process.env.EXPO_ROUTER_APP_ROOT = appDir;

const config = getDefaultConfig(projectRoot);

// Watch monorepo packages
config.watchFolders = [monorepoRoot];

// Resolve from local and root node_modules
config.resolver.nodeModulesPaths = [
  path.resolve(projectRoot, 'node_modules'),
  path.resolve(monorepoRoot, 'node_modules'),
];

// Pin React singletons so every module — including react-native-web from the
// root node_modules — resolves to the same copy (apps/mobile/node_modules).
// Without this, Metro uses the standard Node resolution for root packages and
// ends up with React 18.3.x (root) alongside React 18.2.x (app), which breaks
// the React element identity check and throws "Objects are not valid children".
config.resolver.extraNodeModules = {
  react: path.resolve(projectRoot, 'node_modules', 'react'),
  'react-dom': path.resolve(projectRoot, 'node_modules', 'react-dom'),
  'react-native': path.resolve(projectRoot, 'node_modules', 'react-native'),
};

// --- Fix: expo-router monorepo EXPO_ROUTER_APP_ROOT substitution ---
// babel-preset-expo's expo-router-plugin does not reliably replace
// process.env.EXPO_ROUTER_APP_ROOT in monorepo setups because the
// babel-transformer.js caller is not forwarding customTransformOptions
// before collectDependencies validates require.context arguments.
// Solution: wrap the Babel transformer and pre-patch _ctx.web.js.
const upstreamBabelTransformer = config.transformer.babelTransformerPath;
const patchedTransformerPath = path.resolve(projectRoot, 'metro-babel-transformer.js');

const EXPO_ROUTER_ENTRY = require.resolve('expo-router/entry');
const EXPO_ROUTER_DIR = path.dirname(EXPO_ROUTER_ENTRY);
const relAppRoot = path.relative(EXPO_ROUTER_DIR, appDir).replace(/\\/g, '/');

// Write the wrapper transformer (generated so it always reflects current paths)
fs.writeFileSync(
  patchedTransformerPath,
  `// Auto-generated by metro.config.js — do not edit manually.
const path = require('path');
const upstream = require(${JSON.stringify(upstreamBabelTransformer)});
const ABS_APP_ROOT = ${JSON.stringify(appDir)};
const REL_APP_ROOT = ${JSON.stringify(relAppRoot)};

module.exports = {
  ...upstream,
  transform(opts) {
    if (/expo-router[\\\\/]_ctx\\.web\\.js$/.test(opts.filename)) {
      opts = {
        ...opts,
        src: opts.src
          .replace(/process\\.env\\.EXPO_ROUTER_ABS_APP_ROOT/g, JSON.stringify(ABS_APP_ROOT))
          .replace(/process\\.env\\.EXPO_ROUTER_APP_ROOT/g, JSON.stringify(REL_APP_ROOT))
          .replace(/process\\.env\\.EXPO_ROUTER_IMPORT_MODE/g, JSON.stringify('sync')),
      };
    }
    return upstream.transform(opts);
  },
};
`,
  'utf8'
);

config.transformer.babelTransformerPath = patchedTransformerPath;

module.exports = config;
